### ISSUE TITLE
Some ideas for demonstration purposes

### ISSUE THREAD

**Issue by garyng** [ksk102/RSA-Digital_Signature#1]
_Edit: I fat-fingered and pressed enter without content_

Maybe use something like `jupyter notebook` if doing a gui will take a lot of time?

**Comment by ksk102** [comment]
will discuss the whole thing again with you when we meet.

**Comment by garyng** [comment]
Sure. Better if we do it inside Whatsapp group though.

**Comment by ksk102** [comment]
Yup, will notify the group later in a few minutes

**Comment by garyng** [comment]
[We have a Trello board also](https://trello.com/b/Kxr92oFt/tac3121-applied-cryptography)

**Comment by garyng** [comment]
Closing this! Miss you!
